#!/bin/bash
set -e

if [ "$#" -ne 3 ]; then 
	"$PAK_C_MAK_COMMANDS_PATH/pak-c-mak-help" >&2
	exit 1;
fi

REPO=$1
GIT_URL=$2
GIT_BRANCH=$3

"$PAK_C_MAK_TOOLS_PATH/download-repository-content" $REPO "$GIT_URL" $GIT_BRANCH

mkdir -p "$PAK_C_MAK_REPOSITORIES_META_DB_PATH"

echo \
"REPO=${REPO}
GIT_URL=${GIT_URL}
GIT_BRANCH=${GIT_BRANCH}" >"$PAK_C_MAK_REPOSITORIES_META_DB_PATH/repo-meta-${REPO}"

if [ -f "$PAK_C_MAK_REPOSITORIES_LIST_FILE" ]; then
	REPO_LIST=$(cat "$PAK_C_MAK_REPOSITORIES_LIST_FILE")
	
fi

REPO_LIST=$(echo "$REPO_LIST" | grep -Fvx $REPO)
echo "$REPO_LIST"$'\n'"$REPO" > "$PAK_C_MAK_REPOSITORIES_LIST_FILE"
sed -i '/^$/d' "$PAK_C_MAK_REPOSITORIES_LIST_FILE"
