#!/bin/bash

if [ "$#" -ne 0 ]; then 
	"$PAK_C_MAK_COMMANDS_PATH/pak-c-mak-help" >&2
	exit 1;
fi

if [ -f "$PAK_C_MAK_REPOSITORIES_LIST_FILE" ]; then
	cat "$PAK_C_MAK_REPOSITORIES_LIST_FILE"
else
	"$PAK_C_MAK_PRINT_ERRORS_PATH/no-repo-installed"
	exit 1;
fi
