#!/bin/bash

if [ "$#" -ne 0 ]; then 
	"$PAK_C_MAK_COMMANDS_PATH/pak-c-mak-help"
	exit 1;
fi

if [ -f "$PAK_C_MAK_REPOSITORIES_LIST_FILE" ]; then
	cat "$PAK_C_MAK_REPOSITORIES_LIST_FILE"
else
	echo "No repository installed, "
	echo "   to install repo with packages "
	echo "      please use following command:"
	echo "         pak-c-mak add-repo ..."
	echo "    pak-c-mak help - for more details"
fi


