#!/bin/bash

if [ "$#" -ne 0 ]; then 
	"$PAK_C_MAK_PATH/commands/pak-c-mak-help"
	exit 1;
fi

PACKAGES_DIR=$PAK_C_MAK_PATH/packages/

if [ -d "$PACKAGES_DIR" ]; then
	ls -1 "$PACKAGES_DIR" | perl -wlne 'print $1 if /install-(.*)\.sh/'; 
else
	echo "No repository installed, "
	echo "   to install repo with packages "
	echo "      please use following command:"
	echo "         pak-c-mak add-repo ..."
	echo "    pak-c-mak help - for more details"
fi


