#!/bin/bash
if [ "$#" -ne 0 ]; then 
	"$PAK_C_MAK_COMMANDS_PATH/pak-c-mak-help" >&2
	exit 1;
fi

if [ -d "$PAK_C_MAK_PROFILES_PATH" ]; then
	ls -1 "$PAK_C_MAK_PROFILES_PATH" | perl -wlne 'print $1 if /profile-(.*)/'; 
fi
