#!/bin/bash

if [ "$#" -ne 0 ]; then 
	"$PAK_C_MAK_COMMANDS_PATH/pak-c-mak-help" >&2
	exit 1;
fi

if [ -d "$PAK_C_MAK_PACKAGES_PATH" ]; then
	ls -1 "$PAK_C_MAK_PACKAGES_PATH" | perl -wlne 'print $1 if /install-(.*)/'; 
else
	"$PAK_C_MAK_PRINT_ERRORS_PATH/no-repo-installed"
	exit 1;
fi


