#!/bin/bash

echo "pak-c-mak <command> ..."; 
echo "  pak-c-mak help - prints this message"
echo "  pak-c-mak list - enumarates list of available packages";
echo "  pak-c-mak install <package-name> - installs packages";
echo "  pak-c-mak add-repo <repo-name> <git-url> <git-branch> - addd repository with packages";
echo "  pak-c-mak repo-list - enumarates list of imported repositories";
echo "  pak-c-mak sync-repo [repo-name]- re-imported packages from repositories";
echo "  pak-c-mak profiles-list - prints list of available profiles";
echo "  pak-c-mak cache-path - prints path to cache with installed artifacts";
echo "  pak-c-mak clean-temp - clean temp folder with downloaded packages and build cache";
echo "";
echo "Environment variables:"
echo "  Please, use export command to share variable with pak-c-mak scripts"
echo "    PAK_C_MAK_PATH - "
echo "    PAK_C_MAK_CMAKE_GENERATOR - " 
echo "    PAK_C_MAK_CMAKE_ARGUMENTS - "
echo "    PAK_C_MAK_CMAKE_BUILD_ARGUMENT - "
echo "    PAK_C_MAK_LOCAL_PACKAGES - "
echo "    PAK_C_MAK_PROFILES - "
echo "    PAK_C_MAK_CACHE_POSTFIX -"
