#!/bin/bash
if [ "$#" -ne 1 ]; then 
   echo "cmake-install <project>"; exit 1;
fi

PROJECT=$1

source "$PAK_C_MAK_PATH/pak-c-mak-env"

PROJECT_DIR=$("$PAK_C_MAK_PATH/tools/find-downloaded-content" packages $PROJECT)

mkdir -p "$PROJECT_DIR/build"
cd "$PROJECT_DIR/build"
rm -rf *

cmake $CMAKE_ARGUMENTS -DCMAKE_INSTALL_PREFIX="$CMAKE_PREFIX_PATH" ..

cmake --build . --target INSTALL
cmake --build . --config Release --target INSTALL
