#!/bin/bash
if [ "$#" -ne 4	 ]; then 
   echo "download-git-clone <type> <name> <git-url> <git-branch>"; exit 1;
fi

TYPE=$1
NAME=$2
GIT_URL=$3
GIT_BRANCH=$4

PROJECT_DOWNLOAD_DIR=$("$PAK_C_MAK_TOOLS_PATH/find-downloaded-content" $TYPE $NAME)
if  [[ $PAK_C_MAK_LOCAL_PACKAGES =~ (^|[[:space:]])$NAME($|[[:space:]]) ]] || [[ $PAK_C_MAK_LOCAL_PACKAGES = '*' ]] ; then
	DOWNLOADABLE_NAME=$(realpath "$PAK_C_MAK_PATH/../$NAME")
	
	if [ -d "$DOWNLOADABLE_NAME" ]; then
		exit 0;
	else
		echo '$PAK_C_MAK_LOCAL_PACKAGES is set to' $NAME >&2 ;
		echo "But $DOWNLOADABLE_NAME not found" >&2 ;
		echo "Fallback to git url: $GIT_URL" >&2 ;
	fi
fi

if [ -d "$PROJECT_DOWNLOAD_DIR" ]; then
	if [ ! -d "$PROJECT_DOWNLOAD_DIR/.git" ]; then
		rm -rf "$PROJECT_DOWNLOAD_DIR"
	fi
fi
 

if [ -d "$PROJECT_DOWNLOAD_DIR" ]; then
	#rm -rf "$PROJECT_DOWNLOAD_DIR"
	cd "$PROJECT_DOWNLOAD_DIR"
	git fetch origin $GIT_BRANCH
	git checkout -B $GIT_BRANCH origin/$GIT_BRANCH
else 
	git clone --depth 1 -b $GIT_BRANCH "$GIT_URL" "$PROJECT_DOWNLOAD_DIR"
fi


