#!/bin/bash
if [ "$#" -ne 3	 ]; then 
   echo "download-recursive-copy <type> <name> <path>" >&2; exit 1;
fi

TYPE=$1
NAME=$2
SOURCE_PATH=$(realpath "$3")

PROJECT_DOWNLOAD_DIR=$("$PAK_C_MAK_TOOLS_PATH/find-downloaded-content" $TYPE $NAME)
mkdir -p "$PROJECT_DOWNLOAD_DIR"
cp -af "$SOURCE_PATH"/* "$PROJECT_DOWNLOAD_DIR"
