#!/bin/bash
if [ "$#" -ne 3	 ]; then 
   echo "download-repository-content <repository> <git-url> <git-branch>" >&2; exit 1;
fi

set -e

REPO=$1
GIT_URL=$2
GIT_BRANCH=$3

echo Syncing $REPO from $GIT_URL and $GIT_BRANCH

DOWNLOADABLE_TYPE=repos
DOWNLOADABLE_NAME=$REPO

source "$PAK_C_MAK_TOOLS_PATH/find-downloaded-content"
REPO_DIR="$PACKAGE_DIRECTORY_PATH"

"$PAK_C_MAK_TOOLS_PATH/download-git-clone" repos $REPO "$GIT_URL" $GIT_BRANCH
mkdir -p "$PAK_C_MAK_PACKAGES_PATH/" 
cp -rf "$REPO_DIR"/packages/* "$PAK_C_MAK_PACKAGES_PATH/" 

if [ -d "$REPO_DIR/profiles" ]; then
	mkdir -p "$PAK_C_MAK_PROFILES_PATH"
	cp -rf "$REPO_DIR"/profiles/* "$PAK_C_MAK_PROFILES_PATH";
fi

mkdir -p "$PAK_C_MAK_REPOSITORIES_META_DB_PATH"
