#!/bin/bash
if [ "$#" -ne 2 ]; then 
  echo "find-downloaded-content <content-type> <content-id>" >&2 ; exit 1;
fi

TYPE=$1
NAME=$2

if [[ $PAK_C_MAK_LOCAL_PACKAGES =~ (^|[[:space:]])$NAME($|[[:space:]]) ]]; then
	DOWNLOADABLE_NAME=$(realpath "$PAK_C_MAK_PATH/../$NAME")
	
	if [ ! -d "$DOWNLOADABLE_NAME" ]; then
		echo '$PAK_C_MAK_LOCAL_PACKAGES is set to' $NAME >&2 ;
		echo "But $DOWNLOADABLE_NAME not found" >&2 ;
		exit 1;
	fi

	echo $DOWNLOADABLE_NAME
else
	echo $PAK_C_MAK_PATH/pak_c_mak_tmp/downloads/$TYPE/$NAME
fi



