#!/bin/bash
if [ "$#" -ne 2 ]; then 
  echo "find-downloaded-content <content-type> <content-id>" >&2 ; exit 1;
fi

TYPE=$1
NAME=$2

if  [[ $PAK_C_MAK_LOCAL_PACKAGES =~ (^|[[:space:]])$NAME($|[[:space:]]) ]] || [[ $PAK_C_MAK_LOCAL_PACKAGES = '*' ]] ; then
	DOWNLOADABLE_NAME=$(realpath "$PAK_C_MAK_PATH/../$NAME")
	
	if [ -d "$DOWNLOADABLE_NAME" ]; then
		echo $DOWNLOADABLE_NAME
		exit 0;
	fi
fi

echo $PAK_C_MAK_PATH/pak_c_mak_tmp/downloads/$TYPE/$NAME



