#!/bin/bash
if [ "$#" -ne 3 ]; then 
   echo "git-cmake-install <project> <git-url> <git-branch>" >&2; exit 1;
fi

set -e

PROJECT=$1
GIT_URL=$2
GIT_BRANCH=$3

"$PAK_C_MAK_TOOLS_PATH/download-git-clone" packages $PROJECT "$GIT_URL" master
"$PAK_C_MAK_TOOLS_PATH/cmake-install" $PROJECT